name: Rékka CI

on:
  push:
    branches: [Develop]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - run: npm ci
      - run: npm test
